### ISSUE TITLE
Token generated by @csrf tag not changed per-session

### ISSUE THREAD

**Issue by mutr** [EFTEC/BladeOne#103]
According to this code csrf token passed to template cache and never updated during client interaction. It must be updated per-session or even per-request. https://owasp.org/www-project-cheat-sheets/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html

```php
    protected function compilecsrf()
    {
        return $this->phpTag . " echo '<input type=\"hidden\" name=\"_token\" value=\"" . $this->csrf_token . "\"/>';?>";
    }
```

Also if you check only client ip it is not covered clients behind the proxy/nat and server behind load balancer.

```php
    public function csrfIsValid()
    {
        if (@$_SERVER['REQUEST_METHOD'] == 'POST') {
            $this->csrf_token = @$_POST['_token'];
            return $this->csrf_token . "|" . $this->ipClient() == @$_SESSION["_token"];
        } else {
            if ($this->csrf_token == "") {
                // if not token then we generate a new one
                $this->regenerateToken();
            }
            return true;
        }
    }
```

**Comment by jorgecc** [comment]
OWASP is wrong again.

CSRF fails if you generate a new one per request if your site uses AJAX, so it is the reason why the token is generated once per GET instead of once per request.

Anyways, I added a new argument to the method 

```php
    $blade->csrfIsValid(true);  // new token per request.
```

**Comment by mutr** [comment]
Thank you for fast answer. But please, look at this code carefully. I spent a hour trying to figure out why my token not changed even if I request it. Then I found that my token compiled to ".bladec" file :)

```php
    protected function compilecsrf()
    {
        return $this->phpTag . " echo '<input type=\"hidden\" name=\"_token\" value=\"" . $this->csrf_token . "\"/>';?>";
    }
```

```
<form method="post">
 <?php  echo '<input type="hidden" name="_token" value="b2b124b6ea9b4d05264f"/>';?>
 <input type="text" name="field" value="<?php echo static::e($field); ?>" /><br/>
```

**Comment by jorgecc** [comment]
You could check the example here

https://github.com/EFTEC/BladeOne/blob/master/examples/testtoken.php

@csrf is dummy, it doesn't do any worthy but tho show a simple hidden field with the token already calculated.

The token is generated when it is validated BladeOne::csrfIsValid() in the server side because if the csrf is invalid, then we could redirect, stop the execution, returns an error 304, etc.


```php
$blade=new BladeOne();
$isvalid=$blade->csrfIsValid(false); 
echo $blade->run("Test.token", ['isValid'=>$isvalid]);
```

template test\token.blade.php

```html
<form method="post">
    @csrf
    @if($isValid)
        <hr>Token is valid<hr>
    @else
        <hr><span style="background-color:red">Token ERROR</span><hr>
    @endif()
</form>
```

**Comment by mutr** [comment]
>@csrf is dummy, it doesn't do any worthy but tho show a simple hidden field with the token already calculated.

But what the point of @csrf tag then? I think it is useless in real applications because it shows token generated **once after template changed**, nothing more. So every users see the same token. Token must be generated per-session not per-template generation. I changed issue title.

**Comment by jorgecc** [comment]
The token is generated in the back code, not in the template.

why?

a) As I said, if you do AJAX, then our code needs to do many requests using the same token, so it is not possible to generate a token per request.
b) The validation could be done before the template is even displayed.

So who does the magic is the method: csrfIsValid(), not the tag @token

And no, users do not use the same token because it is generated by csrfIsValid() unless you are not generating it.

Plus, this method requires a session, the template system does not open the session automatically (neither it closes it automatically).

**Comment by mutr** [comment]
I think that I still could not convey my point of view. This is my last attempt :)

```diff
1718c1718
<         return $this->phpTag . " echo '<input type=\"hidden\" name=\"_token\" value=\"" . $this->csrf_token . "\"/>';?>";
---
>         return "<input type=\"hidden\" name=\"_token\" value=\"" . $this->phpTag . "echo \$this->csrf_token; " . "?>" . '"/>';
```

Result:
```diff
<     <?php  echo '<input type="hidden" name="_token" value="f4f85d792a6b94ad4702"/>';?>
---
>     <input type="hidden" name="_token" value="<?php echo $this->csrf_token; ?>"/>
```

**Comment by jorgecc** [comment]
It is a different issue related to the mode of BladeOne

https://github.com/EFTEC/BladeOne#setmode

If you are executing it in mode BladeOne::MODE_SLOW or BladeOne::MODE_DEBUG, then it works. But if you are executing in mode BladeOne::MODE_FAST then it will fail.

#3.36
