### ISSUE TITLE
use of eval()

### ISSUE THREAD

**Issue by kezenwa** [EFTEC/BladeOne#139]
How do we eliminate use of `eval()` which isn't just a source of security worries BUT equally, most times disAbled in  all shared webHosts.

The **public** method `runString($string, $data = [])` and **protected** method `evaluateText($content, $variables)` both uses `eval()`

**Comment by SkoricIT** [comment]
How do you "run a string" or "evaluate text" without eval ?

**Comment by jorgecc** [comment]
> How do we eliminate use of `eval()` which isn't just a source of security worries BUT equally, most times disAbled in all shared webHosts.
> 
> The **public** method `runString($string, $data = [])` and **protected** method `evaluateText($content, $variables)` both uses `eval()`

It is not possible because this library uses heavily reflection and not only eval but other operations.

Also, I can't sponsor the nonsense of some hosting companies.  If the user has access to write PHP code in the server, then it is game-over, no matter if they are restricted to use eval() or not.  AFAIK, you can enable to disable it in the Cpanel, however, some free hosting restricts everything. BladeOne nor Laravel will never be compatible with it.

**Comment by SkoricIT** [comment]
@jorgecc I assumed that this is just something to be closed. Thanks for answering anyway :slightly_smiling_face:

**Comment by jorgecc** [comment]
In short, you can't avoid both functions because they are not vital.
