### ISSUE TITLE
x-template support

### ISSUE THREAD

**Issue by johannesronaldsson** [EFTEC/BladeOne#141]
Hi,

At first, thanks so much for this great library! really helped me with a lot of projects :)
But the only thing I am really missing is the x-template support. 
Is there any future prospect for this?

Thanks in any way!

**Comment by jorgecc** [comment]
Hi there:
The goals of BladeOne are two:
* A slim implementation of the template system of Laravel.
* To push the performance of the implementation of Laravel

In this case, x-template is slow because the implementation of Laravel is not aimed at the performance but at a syntax-sugar.

The concept of Blade (and BladeOne) is simple, you write some template, and it is compiled in native PHP code (you can check the result in the compile folder), for example:
<b>`{!! $variable !!}`</b>
is turned into
`<b><?PHP echo $variable;?></b>`

x-template is different. it relies on some nasty class with inheritances, reflections and such.  X-template could be useful but for this project is a hard pass.  

Also, it is possible to create a new component in BladeOne, there are several ways to do that.

You can use @component

https://github.com/EFTEC/BladeOne/wiki/Template-Component

Or you can create a new tag as (recommended)

https://github.com/EFTEC/BladeOne/wiki/Extending-the-class
