### ISSUE TITLE
About the return values with type hinting.

### ISSUE THREAD

**Issue by juneszh** [EFTEC/BladeOne#149]
Hello, I found the directions about 'type hinting' in version 4.4:
`However, it affects the performance (type hinting validates values). I add type hinting for return values but I can't add type hinting for the arguments without affecting the performance. Instead, I will stay with PHPDOCS.

If considering performance, why return values don't keep stay with PHPDOCS? Otherwise it will also trigger validation. Thx.

**Comment by jorgecc** [comment]
I checked the performance and it is affected in less than 0.0000035 seconds and only in the compilation stage (i.e. once per template).

## Bladeone has two stages:
* The first stage is where the library reads the template, process it and compile it.
* And the second stage where uses the compiled version.  The compiled version is native PHP with a few called to some methods, but in general, it is native PHP code.

## For example this tag:
```html
{{$variable}}
```
it calls the method BladeOne::compileRegularEchos() once and is compiled into:
```php
<?php echo \htmlentities($variable, ENT_QUOTES, 'UTF-8', false); ?
```

So if add type hintings for the method called, it only affects the compilation. However, the compilation is one done once.

```php
    protected function compileRegularEchos($value): string
    {
        $pattern = \sprintf('/(@)?%s\s*(.+?)\s*%s(\r?\n)?/s', $this->contentTags[0], $this->contentTags[1]);
        $callback = function ($matches) {
            $whitespace = empty($matches[3]) ? '' : $matches[3] . $matches[3];
            $wrapped = \sprintf($this->echoFormat, $this->compileEchoDefaults($matches[2]));
            return $matches[1] ? \substr($matches[0], 1) : $this->phpTagEcho . $wrapped . '; ?>' . $whitespace;
        };
        return \preg_replace_callback($pattern, $callback, $value);
    }
```

Every type-hinting affects the performance (in my machine) 0.000000019 seconds per type hinting, so even if we call a method 1 million times, the performance hit will be lower than a fraction of seconds.

## So, what are we gaining adding type hinting? 
Nothing. 

But PHP 8.1 changed the rules. PHP 8.1 is going in the right way of **sound null safety**.

Right now, this library allows passing a string, a number of a null as an argument, then it calls PHP functions and it does the operation.  However, PHP 8.1 is changing that, and some core functions are less liberal and they don't allow to pass a string or null indistinctly anymore (it raises a deprecated warning).

Example, this function:

```php
    public function isQuoted($text): bool
    {
        if (!$text || strlen($text) < 2) {
            return false;
        }
        if ($text[0] === '"' && substr($text, -1) === '"') {
            return true;
        }
        return ($text[0] === "'" && substr($text, -1) === "'");
    }
```

In PHP < 8.1 isQuoted(null) works correctly. However, in PHP 8.1, it raises a deprecated warning because substr() does not allow the first argument is null.

Type hinting for the return method is the first step.

**Comment by juneszh** [comment]
@jorgecc 
Thanks for your detailed answer.
Our production environment is still using PHP 7.4, but it's time to prepare for PHP 8. 🍻
