### ISSUE TITLE
asset() not working

### ISSUE THREAD

**Issue by MasonFI** [EFTEC/BladeOne#22]
It seems asset() function is not in BladeOne yet. Is there any way to inlcude .css and .js files from under /public with BladeOne?

**Comment by jorgecc** [comment]
AFAIK Asset() is not part of the specification of Blade but of Laravel.

Anyways, i added Asset() because it could be util.  Check the readme in how to use it.  BladeOne doesn´t add a base url automatically, because there is not a safe way to do that.

Additionally, you could use your own function as {!! myfunctionasset('url') !!}

Also, you could use:  html-base tag

https://www.w3schools.com/tags/tag_base.asp

**Comment by MasonFI** [comment]
Thanks!
