### ISSUE TITLE
composer.json was rollback???

### ISSUE THREAD

**Issue by neatstudio** [EFTEC/BladeOne#26]
In old version:
```
"eftec\\bladeone\\": "/"
```
and now :
```
"eftec\\": "vendor/eftec/"
```

**Comment by jorgecc** [comment]
It shouldn't be part of the root folder, so it was wrong.

**Comment by Johntaa** [comment]
when you require this repository , the composer will generate  from this repository a psr4 composer file and saved it at  `/vendor/composer/autoload_psr4.json` ,  and this file will contain a wrong path (Namespace) as following:

    'eftec\\' => array($vendorDir . '/eftec/bladeone/vendor/eftec'),  

and this is completely wrong because there is no such path (`eftec/bladeone/vendor/eftec`).

you can see this also in `autoload_static.php` which is in the same folder (/vendor/composer) and you will see the generated path  like this:  

    'eftec\\' => 
        array (
            0 => __DIR__ . '/..' . '/eftec/bladeone/vendor/eftec',
        ),  

which is also misleading path.
Now, to correct this just put it to point to the current folder 
    "eftec\\bladeone\\": "/"  
this will generate the right path in the two file . you can check that before.
 Thank you

**Comment by neatstudio** [comment]
when i use PHP:7.0.x , it's correct!

when i use PHP: >= 7.1  , i must add these code to my composer.json
```
        "psr-4":{
            "eftec\\":"vendor/eftec/"
        }
```
