### ISSUE TITLE
Blade is missing the appendSection method

### ISSUE THREAD

**Issue by bassauer-storms-media** [EFTEC/BladeOne#31]
When you use @section and end it up with @append you get:

Uncaught Error: Call to undefined method Blade::appendSection()

because there is a "compileAppend" (which matches the @append) method, but there is no "appendSection" method (which is called from within the compileAppend method)

**Comment by jorgecc** [comment]
I don't know what @Append does because it's not really documented. I'm based on blade

https://laravel.com/docs/5.6/blade

And it doesn't show @append. However, it's in the code of Laravel, so I fixed it on 2.4  and I used the occasion to update all the new features. Most new features are not really as useful.

**Comment by bassauer-storms-media** [comment]
thank you for adding this to bladeone!

explaination of append:

@section('modals')
.. modal 1 markup
@endsection

@section('modals')
.. modal 2 markup
@endsection

@yield('modals')

=> ".. modal 1 markup"

============

@section('modals')
.. modal 1 markup
@append

@section('modals')
.. modal 2 markup
@append

@yield('modals')

=> ".. modal 1 markup..modal 2 markup"
