### ISSUE TITLE
IF @_e with Lang

### ISSUE THREAD

**Issue by ar3s** [EFTEC/BladeOne#39]
Hi,
first of all I want to thank you for the project. I really think is a great plugin.
I have a little problem that i can't understand. I'm using bladeone with lang and I can't find a way to do something like this:

**<a href="blabla">{!! ($var == 1) ? @_e('Link Name') : '' !!}</a>**

basically @_e('Link Name') always return me an error:
Parse error: syntax error, unexpected '<' in ...

I've also try '@_e('Link Name')'  the error is:
Parse error: syntax error, unexpected 'Link' (T_STRING) in ...

Or: '@_e(Link Name)' in this case does not return an error but it prints:
_e(Link Name); ?>

Changeing to this:
<a href="blabla">{{ ($key == 1) ? '@_e(Link Name)' : '' }}</a>
prints: < ? php echo $this->_e(Link Name); ?>

How can I have "Link Name" printed correctly with Lang ?

thanks in advence,
Best, Ar3s.

**Comment by jorgecc** [comment]
You can't nest a blade tag inside another blade tag, i.e. {!!  @sometag !!} is not allowed because it's converted on <?php <?php something... ?> ?>  :exclamation:

You could

@if(1==1)
    {!! ($var == 1) ? $this->_e('Hat') : '' !!}
@endif

or create a global function, or inject a class or create your own function.
I'm also working to allows a locator/container Blade::_e('Hat') but it's a wip. :smile:

**Comment by ar3s** [comment]
thanks! 👍
