### ISSUE TITLE
Aliasing for included templates missing?

### ISSUE THREAD

**Issue by AfiMorgan** [EFTEC/BladeOne#68]
I noticed that the last release note said this version is aligned with ver. 5.8, however I cannot find the method for aliasing included views.  It was in ver. 5.7 as well, so it may be located under a different method name that I am unable to find.

To get a clearer understanding, this is what I am referencing: 

> ### Aliasing Includes
> If your Blade includes are stored in a sub-directory, you may wish to alias them for easier access. For example, imagine a Blade include that is stored at resources/views/includes/input.blade.php with the following content:
> 
> `<input type="{{ $type ?? 'text' }}">`
>
> You may use the include method to alias the include from includes.input to input. Typically, this should be done in the boot method of your AppServiceProvider:
> 
> ```
> use Illuminate\Support\Facades\Blade;
> 
> Blade::include('includes.input', 'input');
> ```
> Once the include has been aliased, you may render it using the alias name as the Blade directive:
> 
> `@input(['type' => 'email'])`

source : [https://laravel.com/docs/5.8/blade#including-sub-views](https://laravel.com/docs/5.8/blade#including-sub-views)

**Comment by jorgecc** [comment]
Oh, you are lucky, I am free today.   It is ok with a catch (or more than one).
* This library uses and supports PHP 5.6 at least for this year, and PHP 5.6 won't support functions with the name "**include()**", so I called it "**addInclude()**"

* I added an example on https://github.com/EFTEC/BladeOne/blob/master/examples/testinclude.php

it uses 3 templates

```php
<?php
use eftec\bladeone\BladeOne;

include "../lib/BladeOne.php";
$blade=new BladeOne(null,null, BladeOne::MODE_DEBUG);
/** examples/views/Shared/input.blade.php */
$blade->addInclude('Shared.input', 'input');
/** examples/views/Shared/input2.blade.php */
$blade->addInclude('Shared.input2'); 
/** examples/views/Test/include.blade.php */
echo $blade->run("Test.include", ["title" => "VARIABLE TITLE GOES HERE"]);
```

* The example folder is in .gitignore so it is not included on the composer but you can download it.  

* This method doesn't sound as efficient and you don't want to use in a loop (for example). It's way efficient to create your own method.   It is not because BladeOne, the original Laravel's Blade is way worst (it adds a lot of stuff)

* It is not yet available on packagist.

* It misses the unit test too.

**Comment by jorgecc** [comment]
unit test added

[unit test](https://github.com/EFTEC/BladeOne/blob/master/tests/IncludeTest.php)

**Comment by AfiMorgan** [comment]
@jorgecc Haha...I was wondering how you got it done so quick.
It's working fine on my end.  Ill thumb it up on packagist.
Nice work!  

Thank you!
