### ISSUE TITLE
Adopt coding standards

### ISSUE THREAD

**Issue by jakewhiteley** [EFTEC/BladeOne#80]
Currently the code base is messy and does not follow  any standards, even within the same file.

I propose to move To PSR-2 coding standards throughout.

I also propose to move away from
````php
use function count;
use function array_merge;
use function is_array;
````

in favour of inline escaping global function calls as per [this article](https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/).

The reason to use back slashes over `use function` statements, is that it can be enforced by Travis for future commits, and automated as part of the PR process.

@jorgecc I am willing to create a PR for this, and add a phpcs config and task to keep it up to date if you and other contributors are ok with the idea.

**Comment by jorgecc** [comment]
Pushes
Since I am not a programmer but an entrepreneur, I could agree with changes that allow a proper value to the product or solve a business need. 

In the case of PSR-2, I could care less about the standard. Laravel follows a standard and it's a mess, it's painfully slow but hey, the code is nice and it has 800 classes with inheritance and such!.  Ergo, I created a template system for this reason.  I checked the original blade library and nobody has put any love on it since 6 months ago (but some comments).

So, if the PSR-2 means to refactor and clean the code, then it is welcomed. But if it means to add more code(that adds zero value to the code or slow the performance) or other fancy features, then no.

:-)
