### ISSUE TITLE
Work speed

### ISSUE THREAD

**Issue by alsemyannikow** [EFTEC/BladeOne#92]
Sorry, I don't speak English well.
I use your BaldeOne plugin, but the speed is very low, approximately 1 second more. Are there any solutions to the problem?

**Comment by jorgecc** [comment]
When you create the BladeOne object

`$blade = new bladeone\BladeOne($views,$cache,BladeOne::MODE_AUTO);`

You could change the mode of execution
The MODE_AUTO (default mode) check if the template was compiled. If it was, then it does nothing.  The MODE_FAST does not check (it is for production).  

`$blade = new bladeone\BladeOne($views,$cache,BladeOne::MODE_FAST);`

Both modes (AUTO and FAST) give the best performance (however FAST is better). The mode SLOW and DEBUG are slow because they compile the template each time, they are used to develop.
