### ISSUE TITLE
Lang After version 3.19 doesn't work

### ISSUE THREAD

**Issue by ar3s** [EFTEC/BladeOne#94]
Hi, I've updated to version 3.4 and then lower down till version 3.20 but I'm not able to run lang correctly basically it seems like @_e does not read from the $dictionary defined in .php file. 

Text is not translated.
Before 3.20 (3.19 and lower) it was working.

any clue?
thanks

**Comment by jorgecc** [comment]
I added a new version 3.31

However, it doesn't address the problem directly.

It is the solution:

It is the original language file: (for example jp.php, es.php, etc.)

´´´php
BladeOneLang::$dictionary=array(...);
´´´´

The problem is BladeOneLang is a trait, and this value is kept in the trait. However, it is not inherited. 🤷

So, there are many solutions: (that involves changing the dictionary).

# In the dictionary, use the class instead of the trait

´´´php
class myBlade extends BladeOne
{
    use BladeOneLang;
}

myBlade ::$dictionary=array(...); // myBlade istead of BladeOneLang:
´´´

# In the dictionary (again), use the instance instead of the trait

´´´php
class myBlade extends BladeOne
{
    use BladeOneLang;
}

$blade=new myBlade();

$blade::$dictionary=array(...);
´´´
# (new functionality).  BladeOne includes the functionalities of BladeOneLang.

BladeOneLang is not needing anymore. So we don't need to create add the trait

´´´php

$blade=new BladeOne();

$blade::$dictionary=array(...);
´´´

**Comment by ar3s** [comment]
thanks Jorge, 
that's awesome. I will use the new functionality.
Keep up the good job!
